language: python
python:
- 3.6
cache: pip
sudo: required
services:
- docker
jobs:
  include:
  - stage: Refresh domain lists
    script: ".travis/refresh-domains.sh"
    name: Refresh list of domains
  - stage: Build new image
    script: ".travis/build-docker.sh"
    name: "\U0001F433 Build Docker image"
before_install:
- openssl aes-256-cbc -K $encrypted_6f3812c66ea4_key -iv $encrypted_6f3812c66ea4_iv
  -in .travis/ssh-key.enc -out .travis/ssh-key -d
