name: Refresh domain listing
on:
  #schedule:
  #  - cron: '22 1 * * *'
  - push
jobs:
  refresh_domains:
    name: Refresh domains
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Refresh domains listing
        run: bash cron/compile-domain-list.sh

      - name: Count added domains
        run: echo "added_count=$(wc -l src/lists/added.txt | cut -f 1 -d ' ')" >> $GITHUB_ENV

      - name: Count deleted domains
        run: echo "deleted_count=$(wc -l src/lists/deleted.txt | cut -f 1 -d ' ')" >> $GITHUB_ENV
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "CI CRON: Update domain lists (${{ env.added_count }} added; ${{ env.deleted_count }} deleted)"
          file_pattern: 'src/lists/*'
