name: Refresh domain listing
on:
  schedule:
    - cron: '22 1 * * *'
jobs:
  refresh_domains:
    name: Refresh domains
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit changed files
